name: harrypotter_app
description: Harry Potter Web App - A magical app for Harry Potter fans. Created by IMAN.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_web_plugins:
    sdk: flutter
  
  # UI and Animation
  flutter_animate: ^4.0.0
  
  # State Management
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
